/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicGalleryRouteImport } from './routes/_public/gallery'
import { Route as PublicQuoteRouteImport } from './routes/_public/quote'
import { Route as PublicServicesRouteImport } from './routes/_public/services'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminCompanyRouteImport } from './routes/admin/company'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as PublicMachinesIndexRouteImport } from './routes/_public/machines/index'
import { Route as PublicMachinesSlugRouteImport } from './routes/_public/machines/$slug'
import { Route as PublicProjectsIndexRouteImport } from './routes/_public/projects/index'
import { Route as PublicProjectsSlugRouteImport } from './routes/_public/projects/$slug'
import { Route as AdminEnquiriesIdRouteImport } from './routes/admin/enquiries/$id'
import { Route as AdminMachinesIndexRouteImport } from './routes/admin/machines/index'
import { Route as AdminMachinesIdRouteImport } from './routes/admin/machines/$id'
import { Route as AdminMachinesNewRouteImport } from './routes/admin/machines/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaIdRouteImport } from './routes/api/media/$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuoteRoute = PublicQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCompanyRoute = AdminCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicMachinesIndexRoute = PublicMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMachinesSlugRoute = PublicMachinesSlugRouteImport.update({
  id: '/machines/$slug',
  path: '/machines/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsSlugRoute = PublicProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminEnquiriesIdRoute = AdminEnquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEnquiriesRoute,
} as any)
const AdminMachinesIndexRoute = AdminMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesIdRoute = AdminMachinesIdRouteImport.update({
  id: '/machines/$id',
  path: '/machines/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesNewRoute = AdminMachinesNewRouteImport.update({
  id: '/machines/new',
  path: '/machines/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/quote': typeof PublicQuoteRoute
  '/services': typeof PublicServicesRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/enquiries': typeof AdminEnquiriesRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/admin/': typeof AdminIndexRoute
  '/machines/$slug': typeof PublicMachinesSlugRoute
  '/projects/$slug': typeof PublicProjectsSlugRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
  '/admin/machines/$id': typeof AdminMachinesIdRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/machines/': typeof PublicMachinesIndexRoute
  '/projects/': typeof PublicProjectsIndexRoute
  '/admin/machines/': typeof AdminMachinesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/quote': typeof PublicQuoteRoute
  '/services': typeof PublicServicesRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/enquiries': typeof AdminEnquiriesRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/machines/$slug': typeof PublicMachinesSlugRoute
  '/projects/$slug': typeof PublicProjectsSlugRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
  '/admin/machines/$id': typeof AdminMachinesIdRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/machines': typeof PublicMachinesIndexRoute
  '/projects': typeof PublicProjectsIndexRoute
  '/admin/machines': typeof AdminMachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/quote': typeof PublicQuoteRoute
  '/_public/services': typeof PublicServicesRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/enquiries': typeof AdminEnquiriesRouteWithChildren
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/machines/$slug': typeof PublicMachinesSlugRoute
  '/_public/projects/$slug': typeof PublicProjectsSlugRoute
  '/admin/enquiries/$id': typeof AdminEnquiriesIdRoute
  '/admin/machines/$id': typeof AdminMachinesIdRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/_public/machines/': typeof PublicMachinesIndexRoute
  '/_public/projects/': typeof PublicProjectsIndexRoute
  '/admin/machines/': typeof AdminMachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/quote'
    | '/services'
    | '/admin/account'
    | '/admin/company'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/seo'
    | '/admin/services'
    | '/api/uploads'
    | '/admin/'
    | '/machines/$slug'
    | '/projects/$slug'
    | '/admin/enquiries/$id'
    | '/admin/machines/$id'
    | '/admin/machines/new'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/machines/'
    | '/projects/'
    | '/admin/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/quote'
    | '/services'
    | '/admin/account'
    | '/admin/company'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/seo'
    | '/admin/services'
    | '/api/uploads'
    | '/'
    | '/admin'
    | '/machines/$slug'
    | '/projects/$slug'
    | '/admin/enquiries/$id'
    | '/admin/machines/$id'
    | '/admin/machines/new'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/machines'
    | '/projects'
    | '/admin/machines'
  id:
    | '__root__'
    | '/admin'
    | '/_public'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/gallery'
    | '/_public/quote'
    | '/_public/services'
    | '/admin/account'
    | '/admin/company'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/seo'
    | '/admin/services'
    | '/api/uploads'
    | '/_public/'
    | '/admin/'
    | '/_public/machines/$slug'
    | '/_public/projects/$slug'
    | '/admin/enquiries/$id'
    | '/admin/machines/$id'
    | '/admin/machines/new'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/_public/machines/'
    | '/_public/projects/'
    | '/admin/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/quote': {
      id: '/_public/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof PublicQuoteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/company': {
      id: '/admin/company'
      path: '/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AdminCompanyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/machines/': {
      id: '/_public/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof PublicMachinesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/machines/$slug': {
      id: '/_public/machines/$slug'
      path: '/machines/$slug'
      fullPath: '/machines/$slug'
      preLoaderRoute: typeof PublicMachinesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects/': {
      id: '/_public/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects/$slug': {
      id: '/_public/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof PublicProjectsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/enquiries/$id': {
      id: '/admin/enquiries/$id'
      path: '/$id'
      fullPath: '/admin/enquiries/$id'
      preLoaderRoute: typeof AdminEnquiriesIdRouteImport
      parentRoute: typeof AdminEnquiriesRoute
    }
    '/admin/machines/': {
      id: '/admin/machines/'
      path: '/machines'
      fullPath: '/admin/machines/'
      preLoaderRoute: typeof AdminMachinesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/machines/$id': {
      id: '/admin/machines/$id'
      path: '/machines/$id'
      fullPath: '/admin/machines/$id'
      preLoaderRoute: typeof AdminMachinesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/machines/new': {
      id: '/admin/machines/new'
      path: '/machines/new'
      fullPath: '/admin/machines/new'
      preLoaderRoute: typeof AdminMachinesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminEnquiriesRouteChildren {
  AdminEnquiriesIdRoute: typeof AdminEnquiriesIdRoute
}

const AdminEnquiriesRouteChildren: AdminEnquiriesRouteChildren = {
  AdminEnquiriesIdRoute: AdminEnquiriesIdRoute,
}

const AdminEnquiriesRouteWithChildren = AdminEnquiriesRoute._addFileChildren(
  AdminEnquiriesRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminCompanyRoute: typeof AdminCompanyRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRouteWithChildren
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMachinesIdRoute: typeof AdminMachinesIdRoute
  AdminMachinesNewRoute: typeof AdminMachinesNewRoute
  AdminMachinesIndexRoute: typeof AdminMachinesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminCompanyRoute: AdminCompanyRoute,
  AdminEnquiriesRoute: AdminEnquiriesRouteWithChildren,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMachinesIdRoute: AdminMachinesIdRoute,
  AdminMachinesNewRoute: AdminMachinesNewRoute,
  AdminMachinesIndexRoute: AdminMachinesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicQuoteRoute: typeof PublicQuoteRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicMachinesSlugRoute: typeof PublicMachinesSlugRoute
  PublicProjectsSlugRoute: typeof PublicProjectsSlugRoute
  PublicMachinesIndexRoute: typeof PublicMachinesIndexRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicQuoteRoute: PublicQuoteRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicMachinesSlugRoute: PublicMachinesSlugRoute,
  PublicProjectsSlugRoute: PublicProjectsSlugRoute,
  PublicMachinesIndexRoute: PublicMachinesIndexRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
